### ISSUE TITLE
[RESTful] study and document RESTful

### ISSUE THREAD

**Issue by andres0sorio** [ecos-codeaholics/factory-of-procedures-back#3]
Before jumping into any coding of the routes that our code will support, review and document the RESTful recommendations.

**Comment by andres0sorio** [comment]
Document in the backend Wiki.

**Comment by jasonlll88** [comment]
Ready 
https://github.com/ecos-codeaholics/factory-of-procedures-back/wiki/RESTful-routes-proposal
http://codeaholics.dynns.com/do/view/Main/RestFulRoutesProposal

but we continuously have to update the information of the routes created.

**Comment by snaphuman** [comment]
Excellent. Now we know how to define and implement endpoint routes to our backend. Great contribution. Thank's
