### ISSUE TITLE
[login] wrong json format in server response

### ISSUE THREAD

**Issue by snaphuman** [ecos-codeaholics/factory-of-procedures-back#5]
Hi!, working at frontend in the user login component and I have found that the response of the server does not provide the correct json format that should be handled by angular to present user messages. This is causing an error in the client side that breaks the template. I'm attaching the request object, the response of the server. Thank's in advance.

**Request**
![login-req-params](https://cloud.githubusercontent.com/assets/246425/17598339/a27233d8-5fbf-11e6-8fcf-6128ea69a5b1.png)

**Response**
![login-res-object](https://cloud.githubusercontent.com/assets/246425/17598349/b496f5ee-5fbf-11e6-82e0-ff14d0ab013b.png)

**Comment by andres0sorio** [comment]
Will look into it Fabian. I suppose this is the answer you get after you send a login request.

**Comment by snaphuman** [comment]
That's right Andrés, this response correspond to login request.
Greetings!

**Comment by andres0sorio** [comment]
Hi. I checked this issue but I cannot see any problem with it. I did three tests: a) I added a Junit test to check on the login procedure (LoginTest) and looked at the return value from the authentication routine (the basic one, no jwt which is supposed to return also a json). b) wrote a python script and checked the return value from the authentication. c) used a Windows free application that sends POST request to the backend. I all cases I get the string as it should. I did modify the response from the backend but using the old one also obtains the same result. Not sure what/where is the bug.

**Comment by andres0sorio** [comment]
Ok I think I understand what is going on: we have to return an Object from our methods. Each response is transformed using the defined ResponseTransformer defined by us in each route:
Example:
post("/citizenLogin", CitizenServices::doLogin, GeneralUtil.json());
Will include this fix at the next development commit.

**Comment by andres0sorio** [comment]
Fix integrated into development branch. please check if it works.

**Comment by andres0sorio** [comment]
I believe this has been fixed already. Closing it.
